### ISSUE TITLE
Background and Spacing issues

### ISSUE THREAD

**Issue by CajSWehst** [CajSWehst/svg-icon-sets#1]
@thatkidmadrid 
@carolsinc

So my website looks good for the most part I am just struggling with the spacing and the background sizing. I don't want to over-code like I did last time so if you could take a look at it and possibly give me some direction. 

Thank you.

**Comment by thatkidmadrid** [comment]
Hey Caj,
I think what you have is good but you could improve the structure and what html tags you're using.
I think you have the right idea that there is a grid and that components are using flex box inside of the grid, but be careful with which items get the `display: flex`

Regarding the background, you can imagine the background not extending the entire screen (I apologize that this wasn't very clear) but instead just wrapping the contents with an even padding. This will get your gradient to match the reference

![Screen Shot 2021-10-17 at 3 43 26 PM](https://user-images.githubusercontent.com/6340290/137642568-d7624d29-2639-4837-8dc2-e4b6f3ec29ce.png)
